name: Calendario RSCE diario

on:
  schedule:
    - cron: '5 4 * * *'   # 04:05 UTC (≈ 06:05 en España en verano)
  workflow_dispatch: {}

jobs:
  run_and_upload:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias (si existe requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar script que genera el CSV
        run: |
          python "./Calendario RSCE 25.08.22.py"

      - name: Detectar CSV generado y calcular hash
        id: csv
        run: |
          set -euo pipefail
          # Rutas habituales; amplía si cambias de carpeta
          CSV_PATH=""
          for p in "resultados_agility/eventos_agility_2025.csv" "eventos_agility_2025.csv"; do
            if [ -f "$p" ]; then CSV_PATH="$p"; break; fi
          done
          if [ -z "$CSV_PATH" ]; then
            CSV_PATH="$(ls -1 **/eventos_agility_2025.csv 2>/dev/null | head -n1 || true)"
          fi
          if [ -z "$CSV_PATH" ]; then
            echo "No se encontró eventos_agility_2025.csv"; exit 1
          fi
          echo "➡ CSV encontrado en: $CSV_PATH"
          echo "csv_path=$CSV_PATH" >> "$GITHUB_OUTPUT"
          sha256sum "$CSV_PATH" | awk '{print $1}' > local.sha256
          echo "Hash local: $(cut -d' ' -f1 local.sha256)"

      - name: Listar carpeta remota (antes de subir)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}        # p.ej. agilitydivertidog-com.espacioseguro.com
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}      # p.ej. agilitydivertidog
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}    # /www/NewWeb/Privado
        run: |
          set -euo pipefail
          LIST_URL="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/Calendar/"
          echo "📂 Listando: $LIST_URL"
          curl --fail --ssl-reqd --user "${FTP_USERNAME}:${FTP_PASSWORD}" "$LIST_URL" -l || true

      - name: Subir y verificar por FTPS (añadiendo /Calendar)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}   # /www/NewWeb/Privado
        run: |
          set -euo pipefail
          BASE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/Calendar"
          FILE="eventos_agility_2025.csv"
      
          echo "📂 Listando antes de subir: ${BASE}/"
          curl --fail --ssl-reqd --user "${FTP_USERNAME}:${FTP_PASSWORD}" "${BASE}/" -l || true
      
          echo "⬆️  Subiendo ${FILE} a ${BASE}/${FILE}"
          curl --fail --ssl-reqd --ftp-create-dirs \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --upload-file "${{ steps.csv.outputs.csv_path }}" \
               "${BASE}/${FILE}"
      
          echo "📂 Listando después de subir:"
          curl --fail --ssl-reqd --user "${FTP_USERNAME}:${FTP_PASSWORD}" "${BASE}/" -l
      
          echo "⬇️  Descargando para comparar hash…"
          curl --fail --ssl-reqd \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --output remote.csv "${BASE}/${FILE}"
      
          sha256sum remote.csv | awk '{print $1}' > remote.sha256
          echo "Local : $(cut -d' ' -f1 local.sha256)"
          echo "Remoto: $(cut -d' ' -f1 remote.sha256)"
          diff -q local.sha256 remote.sha256
          echo "✅ Hash OK"


      - name: Subir copia con fecha (AAAA-MM-DD) (opcional)
        if: always()
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          D=$(date +%F)
          REMOTE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/Calendar/eventos_agility_2025_${D}.csv"
          echo "➡ Subiendo copia fechada a: $REMOTE"
          curl --fail --ssl-reqd \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --upload-file "${{ steps.csv.outputs.csv_path }}" "$REMOTE"
