name: Calendario RSCE diario

on:
  schedule:
    - cron: '5 4 * * *'   # 04:05 UTC
  workflow_dispatch: {}

jobs:
  run_and_upload:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias (si existe requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar script que genera el CSV
        run: |
          python "./Calendario RSCE 25.08.22.py"

      - name: Detectar CSV generado
        id: csv
        run: |
          set -euo pipefail
          CSV_PATH=""
          for p in "resultados_agility/eventos_agility_2025.csv" "eventos_agility_2025.csv"; do
            if [ -f "$p" ]; then CSV_PATH="$p"; break; fi
          done
          if [ -z "$CSV_PATH" ]; then
            CSV_PATH="$(ls -1 **/eventos_agility_2025.csv 2>/dev/null | head -n1 || true)"
          fi
          if [ -z "$CSV_PATH" ]; then
            echo "No se encontró eventos_agility_2025.csv"; exit 1
          fi
          echo "csv_path=$CSV_PATH" >> "$GITHUB_OUTPUT"
          sha256sum "$CSV_PATH" | awk '{print $1}' > local.sha256

      - name: Subir CSV por FTPS (puerto 21, TLS explícito)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}   # ej: /www/NewWeb/Privado/Calendar
        run: |
          set -euo pipefail
          REMOTE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/Calendar/eventos_agility_2025.csv"
          echo "➡ Subiendo a: $REMOTE"
          curl --fail --ssl-reqd --ftp-create-dirs \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --upload-file "${{ steps.csv.outputs.csv_path }}" "$REMOTE"

      - name: Verificar remoto (descargar y comparar hash)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          REMOTE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/eventos_agility_2025.csv"
          curl --fail --ssl-reqd \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --output remote.csv "$REMOTE"
          sha256sum remote.csv | awk '{print $1}' > remote.sha256
          diff -q local.sha256 remote.sha256
          echo "✅ Hash OK"


