name: 01 - Eventos Prox (JSON base)

on:
  schedule:
    - cron: '1 4 * * *'
  workflow_dispatch: {}

jobs:
  produce_01events:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
    steps:
      - uses: actions/checkout@v4

      - name: Mostrar árbol del repo y rama
        run: |
          echo "BRANCH: $GITHUB_REF_NAME"
          git ls-files | sed 's/^/ - /' | head -n 200 || true
          ls -la || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install beautifulsoup4 selenium webdriver-manager

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar 01_eventosprox.py
        env:
          FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
          FLOW_PASS:  ${{ secrets.FLOW_PASS }}
        run: |
          set -euo pipefail
          mkdir -p output
          SCRIPT_PATH="$(find . -maxdepth 3 -type f -name '01_eventosprox.py' -print -quit)"
          if [ -z "${SCRIPT_PATH:-}" ]; then
            echo "::error::No se encontró 01_eventosprox.py en el repo"; exit 1
          fi
          echo "Usando script: $SCRIPT_PATH"
          python "$SCRIPT_PATH"
          test -f ./output/01events.json

      - name: Verificar salida
        run: |
          ls -lh ./output
          python - <<'PY'
          import json,sys
          with open("./output/01events.json","r",encoding="utf-8") as f:
              data=json.load(f)
          print("Eventos:", len(data))
          PY

      - name: Subir artefacto 01events
        uses: actions/upload-artifact@v4
        with:
          name: a01-01events-json
          path: ./output/01events.json
          if-no-files-found: error
          retention-days: 7
