name: 01 - Eventos Prox (JSON base)

on:
  schedule:
    - cron: '1 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

concurrency:
  group: participantes-01
  cancel-in-progress: true

jobs:
  produce_01events:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS:  ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Debug repo
        run: |
          echo "BRANCH: $GITHUB_REF_NAME"
          git ls-files | sed 's/^/ - /' | head -n 200
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install beautifulsoup4 lxml selenium webdriver-manager python-dotenv

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar 01_eventosprox.py
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p output
          SCRIPT_PATH="$(git ls-files | grep -E '(^|/)(01_eventosprox\.py)$' | head -n1 || true)"
          if [ -z "${SCRIPT_PATH:-}" ]; then
            echo "::error::No se encontró 01_eventosprox.py en el repo"; exit 1
          fi
          echo "Usando script: $SCRIPT_PATH"
          python "$SCRIPT_PATH"
          if [ -f ./output/events.json ]; then
            cp -f ./output/events.json ./output/01events.json
          elif [ -f ./output/01events.json ]; then
            :
          else
            echo "::error::No se generó ./output/events.json ni ./output/01events.json"; exit 1
          fi

      - name: Verificar salida local
        run: |
          ls -lh ./output
          test -f ./output/01events.json
          sha256sum ./output/01events.json | awk '{print $1}' > local.sha256
          echo "Hash local: $(cat local.sha256)"

      - name: Subir artefacto (para 02)
        uses: actions/upload-artifact@v4
        with:
          name: a01-01events-json
          path: ./output/01events.json
          if-no-files-found: error
          retention-days: 7

      # ================== FTPS (lftp) ==================
      - name: Instalar lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: (FTPS) Diagnóstico de base remota
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Diagnóstico de ${FTP_SERVER} :: ${FTP_REMOTE_DIR}"
          lftp -u "${FTP_USERNAME},${FTP_PASSWORD}" "${FTP_SERVER}" -e " \
            set cmd:fail-exit true; \
            set net:max-retries 1; \
            set net:timeout 30; \
            set ftp:ssl-force true; \
            set ftp:ssl-protect-data true; \
            set ftp:passive-mode true; \
            set ftp:prefer-epsv false; \
            set ssl:verify-certificate no; \
            pwd; cls -l; \
            cd '${FTP_REMOTE_DIR}' || cd '/${FTP_REMOTE_DIR}'; \
            echo 'PWD tras cd:'; pwd; cls -l; \
            bye"

      - name: (FTPS) Subir y verificar (01events.json)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        shell: bash
        run: |
          set -euo pipefail
          FILE="./output/01events.json"
          [ -f "$FILE" ] || { echo "::error::Falta $FILE"; exit 1; }
          TS="$(date -u +'%Y%m%dT%H%M%SZ')"

          # 1) Subir a la ruta objetivo
          echo "Subiendo a ${FTP_REMOTE_DIR}/Competiciones/ListadoEventos/Workflows/01"
          lftp -u "${FTP_USERNAME},${FTP_PASSWORD}" "${FTP_SERVER}" -e " \
            set cmd:fail-exit true; \
            set net:max-retries 2; \
            set net:timeout 40; \
            set ftp:ssl-force true; \
            set ftp:ssl-protect-data true; \
            set ftp:passive-mode true; \
            set ftp:prefer-epsv false; \
            set ssl:verify-certificate no; \
            cd '${FTP_REMOTE_DIR}' || cd '/${FTP_REMOTE_DIR}'; \
            mkdir -f Competiciones; cd Competiciones; \
            mkdir -f ListadoEventos; cd ListadoEventos; \
            mkdir -f Workflows; cd Workflows; \
            mkdir -f 01; cd 01; \
            put -O . '${FILE}' -o '01events_last.json'; \
            put -O . '${FILE}' -o '01events_${TS}.json'; \
            echo 'Listado tras subida:'; cls -l; \
            bye"

          # 2) Descargar y comparar hashes (verificación dura)
          rm -f remote_last.json remote.sha256 || true
          lftp -u "${FTP_USERNAME},${FTP_PASSWORD}" "${FTP_SERVER}" -e " \
            set cmd:fail-exit true; \
            set net:max-retries 1; \
            set net:timeout 40; \
            set ftp:ssl-force true; \
            set ftp:ssl-protect-data true; \
            set ftp:passive-mode true; \
            set ftp:prefer-epsv false; \
            set ssl:verify-certificate no; \
            cd '${FTP_REMOTE_DIR}' || cd '/${FTP_REMOTE_DIR}'; \
            cd Competiciones/ListadoEventos/Workflows/01; \
            get -O . '01events_last.json' -o 'remote_last.json'; \
            bye"
          sha256sum remote_last.json | awk '{print $1}' > remote.sha256
          echo "Hash remoto: $(cat remote.sha256)"
          diff -q local.sha256 remote.sha256

      - name: (FTPS) Buscar archivos 01events* en todo el árbol del FTP_REMOTE_DIR
        if: always()
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Búsqueda recursiva de 01events*.json bajo ${FTP_REMOTE_DIR}"
          lftp -u "${FTP_USERNAME},${FTP_PASSWORD}" "${FTP_SERVER}" -e " \
            set cmd:fail-exit false; \
            set ftp:ssl-force true; \
            set ftp:ssl-protect-data true; \
            set ftp:passive-mode true; \
            set ftp:prefer-epsv false; \
            set ssl:verify-certificate no; \
            cd '${FTP_REMOTE_DIR}' || cd '/${FTP_REMOTE_DIR}'; \
            cls -1 -R | grep -Ei '(^|/)(01events_.*\.json|01events_last\.json)$' || true; \
            bye"
