name: 01 - Eventos Prox (JSON base)

on:
  schedule:
    - cron: '1 4 * * *'
  workflow_dispatch: {}

jobs:
  produce_01events:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS:  ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install beautifulsoup4 selenium webdriver-manager

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run 01_eventosprox.py
        id: run01
        run: |
          set -euo pipefail
          mkdir -p output
          SCRIPT_PATH="$(find . -maxdepth 3 -type f -name '01_eventosprox.py' -print -quit)"
          [ -n "${SCRIPT_PATH:-}" ] || { echo "::error::No se encontró 01_eventosprox.py"; exit 1; }
          echo "Usando script: $SCRIPT_PATH"
          python "$SCRIPT_PATH"
          echo "Listando output:"
          ls -la ./output || true
          test -f ./output/events.json || { echo "::error::No se generó ./output/events.json"; exit 1; }
          cp -f ./output/events.json ./output/01events.json

      - name: Upload main artifact
        uses: actions/upload-artifact@v4
        with:
          name: a01-01events-json
          path: ./output/01events.json
          if-no-files-found: error
          retention-days: 7

      # Artefactos de depuración si algo va mal (o siempre, si quieres)
      - name: Upload debug (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a01-debug
          path: |
            ./output/**
            ./01_error.png
          if-no-files-found: warn
          retention-days: 7
