name: 02 - INFO desde 01events

on:
  workflow_run:
    workflows: ["01 - Eventos Prox (JSON base)"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  produce_02info:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid

    steps:
      - uses: actions/checkout@v4

      - name: Mostrar árbol del repo y rama (debug)
        run: |
          echo "BRANCH: $GITHUB_REF_NAME"
          git ls-files | sed 's/^/ - /' | head -n 200
          echo "----"; ls -la; echo "---- FIN LISTADO ----"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias (incluye Selenium)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "selenium==4.*" "webdriver-manager==4.*" beautifulsoup4 lxml

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Comprobar Chrome y librerías
        run: |
          set -euo pipefail
          which google-chrome
          google-chrome --version || true
          python -c "import sys,selenium,bs4; print('Python:',sys.version); print('Selenium:',selenium.__version__); print('BS4 OK')"

      # Encadenado: baja artefacto exacto del workflow 01
      - name: Descargar artefacto 01events (modo encadenado)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: a01-01events-json
          path: ./artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Manual: baja el último artefacto del workflow 01 en la rama main
      - name: Descargar artefacto 01events (modo manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/download-artifact@v4
        with:
          name: a01-01events-json
          path: ./artifacts
          workflow: "01 - Eventos Prox (JSON base)"
          branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ejecutar 02_eventosproxINFO.py
        run: |
          set -euo pipefail
          mkdir -p output
          IN="./artifacts/01events.json"
          test -f "$IN" || { echo "::error::No existe $IN"; ls -la ./artifacts || true; exit 1; }

          SCRIPT_PATH="$(find . -maxdepth 5 -type f -name '02_eventosproxINFO.py' -print -quit)"
          if [ -z "${SCRIPT_PATH:-}" ]; then
            echo "::error::No se encontró 02_eventosproxINFO.py"; exit 1
          fi
          echo "Usando script: $SCRIPT_PATH"
          python "$SCRIPT_PATH" "$IN" "./output/02competiciones_detalladas.json"

          test -f ./output/02competiciones_detalladas.json || { echo "::error::No se generó la salida esperada"; exit 1; }
          ls -lh ./output

      - name: Subir artefacto 02info
        uses: actions/upload-artifact@v4
        with:
          name: a02-02info-json
          path: ./output/02competiciones_detalladas.json
          if-no-files-found: error
          retention-days: 7
