name: 03 - Participantes (scrape + process)

on:
  workflow_run:
    workflows: ["02 - INFO desde 01events"]
    types: [completed]
  workflow_dispatch: {}
  schedule:
    - cron: '3 4 * * *'

permissions:
  contents: read
  actions: read

concurrency:
  group: participantes-03
  cancel-in-progress: true

jobs:
  run_and_upload:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      TZ: Europe/Madrid
      OUT_DIR: ./output
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS:  ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
      FILE_PREFIX: "03"
      LIMIT_EVENTS: "0"
      LIMIT_PARTICIPANTS: "0"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager beautifulsoup4 python-dotenv pandas python-dateutil numpy lxml
          fi

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run 03 (all: scrape + process)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p output
          timeout 110m python "./03_eventosproxParticipantes.py" all

      - name: List outputs
        run: |
          ls -la ./output || true
          echo "Processed CSV (latest):"
          ls -1t ./output/participantes_procesado_*.csv 2>/dev/null | head -n1 || true

      - name: Upload artifacts (for 04)
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-processed
          path: |
            output/*events_*.csv
            output/*participantes_*.csv
            output/participantes.json
            output/participantes_*.json
            output/participantes_procesado_*.csv
            output/*progress_*.json
          if-no-files-found: error
          retention-days: 7

      # ===== FTPS (03) =====
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: (FTPS) Upload + verify (03)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        shell: bash
        run: |
          set -euo pipefail
          JSON="./output/participantes.json"
          [ -f "$JSON" ] || { echo "::error::Missing $JSON"; exit 1; }
          CSV="$(ls -1t ./output/participantes_procesado_*.csv 2>/dev/null | head -n1 || true)"
          TS="$(date -u +'%Y%m%dT%H%M%SZ')"
          DEST_BASE="${FTP_REMOTE_DIR%/}"
          DEST_DIR="$DEST_BASE/Competiciones/ListadoEventos/Workflows/03"

          cp -f "$JSON" ./output/03participants_last.json
          sha256sum ./output/03participants_last.json | awk '{print $1}' > local03.sha256

          lftp -u "${FTP_USERNAME},${FTP_PASSWORD}" "${FTP_SERVER}" -e " \
            set cmd:fail-exit true; \
            set net:timeout 25; \
            set net:max-retries 1; \
            set net:persist-retries 0; \
            set ftp:ssl-force true; \
            set ftp:ssl-protect-data true; \
            set ftp:passive-mode true; \
            set ftp:prefer-epsv false; \
            set ssl:verify-certificate no; \
            cd '${DEST_BASE}' || cd '/${DEST_BASE}'; \
            mkdir -f Competiciones; cd Competiciones; \
            mkdir -f ListadoEventos; cd ListadoEventos; \
            mkdir -f Workflows; cd Workflows; \
            mkdir -f 03; cd 03; \
            put -O . './output/03participants_last.json' -o '03participants_last.json'; \
            put -O . './output/03participants_last.json' -o '03participants_${TS}.json'; \
            $( [ -n "$CSV" ] && echo "put -O . '$CSV' -o '03participants_procesado_last.csv';" ); \
            echo 'Destino:'; pwd; cls -l; \
            bye"

          rm -rf dl && mkdir -p dl
          lftp -u "${FTP_USERNAME},${FTP_PASSWORD}" "${FTP_SERVER}" -e " \
            set cmd:fail-exit true; \
            set net:timeout 25; \
            set net:max-retries 1; \
            set net:persist-retries 0; \
            set ftp:ssl-force true; \
            set ftp:ssl-protect-data true; \
            set ftp:passive-mode true; \
            set ftp:prefer-epsv false; \
            set ssl:verify-certificate no; \
            cd '${DEST_DIR}' || cd '/${DEST_DIR}'; \
            get -O '${PWD}/dl' '03participants_last.json'; \
            bye"
          sha256sum dl/03participants_last.json | awk '{print $1}' > remote03.sha256
          diff -q local03.sha256 remote03.sha256
