name: 03 - Participantes (scrape + process)

on:
  # Encadenado automáticamente desde el 02
  workflow_run:
    workflows: ["02 - INFO desde 01events"]
    types: [completed]

  # Lanzamiento manual
  workflow_dispatch: {}

  # (Opcional) cron diario
  schedule:
    - cron: '3 4 * * *'

concurrency:
  group: participantes-03
  cancel-in-progress: true

jobs:
  run_and_upload:
    # Ejecuta si viene manual/cron o si viene encadenado y el 02 terminó OK
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
      OUT_DIR: ./output
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS: ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
      FILE_PREFIX: "03"
      LIMIT_EVENTS: "0"
      LIMIT_PARTICIPANTS: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager beautifulsoup4 python-dotenv pandas python-dateutil numpy
          fi

      - name: Ejecutar 03 (all: scrape + process)
        run: python "./03_eventosproxParticipantes.py" all

      - name: Mostrar outputs
        run: |
          echo "Contenido de $OUT_DIR:"
          ls -la "$OUT_DIR" || true

      - name: Subir artefactos (JSON+CSV)
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-processed
          path: |
            output/*events_*.csv
            output/*participantes_*.csv
            output/participantes.json
            output/participantes_*.json
            output/participantes_procesado_*.csv
            output/*progress_*.json
          if-no-files-found: error
          retention-days: 5
