name: 3 - Participantes (scrape + process)

on:
  workflow_run:
    workflows: ["02 - INFO desde 01events"]   # puedes quitar esta dependencia si ya no te interesa
    types: [completed]
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

jobs:
  run_03:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
      # Credenciales que tu script lee con dotenv o env
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS:  ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
      OUT_DIR: "./output"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install selenium python-dotenv pandas python-dateutil numpy

      - name: Setup Chrome (Selenium Manager gestionará el driver)
        uses: browser-actions/setup-chrome@v1

      - name: Run 03_eventosproxParticipantes.py (all)
        run: |
          set -euo pipefail
          mkdir -p "$OUT_DIR"
          SCRIPT_PATH="$(find . -maxdepth 6 -type f -name '03_eventosproxParticipantes.py' -print -quit)"
          [ -n "$SCRIPT_PATH" ] || { echo "::error::No se encuentra 03_eventosproxParticipantes.py"; exit 1; }
          echo "Using: $SCRIPT_PATH"
          python "$SCRIPT_PATH" all

      - name: Verify outputs & list
        run: |
          set -euo pipefail
          ls -la ./output || true
          test -f ./output/participantes.json || echo "::warning::No existe ./output/participantes.json (revisa logs del 03)"

      - name: Upload processed participants (JSON+CSV)
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-processed
          path: |
            ./output/participantes.json
            ./output/participantes_*.json
            ./output/events_*.csv
            ./output/participants_*.csv
            ./output/participantes_procesado_*.csv
            ./output/progress_*.json
          if-no-files-found: warn
          retention-days: 10
