name: 03 Participantes (scrape + process)

on:
  schedule:
    - cron: '3 4 * * *'
  workflow_dispatch: {}

jobs:
  run_and_upload:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
      OUT_DIR: ./output
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS: ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
      FILE_PREFIX: "03"
      LIMIT_EVENTS: "0"
      LIMIT_PARTICIPANTS: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager beautifulsoup4 python-dotenv pandas python-dateutil numpy
          fi

      - name: "Ejecutar 03 (all: scrape + process)"
        shell: bash
        run: |
          set -euo pipefail
          python "./03_eventosproxParticipantes.py" all

      - name: Listado de outputs
        shell: bash
        run: |
          echo "Contenido de $OUT_DIR:"
          ls -la "$OUT_DIR" || true
          echo "Coincidencias previstas:"
          ls -1 ./output/*events_*.csv 2>/dev/null || true
          ls -1 ./output/*participantes_*.csv 2>/dev/null || true
          ls -1 ./output/participantes*.json 2>/dev/null || true
          ls -1 ./output/*progress_*.json 2>/dev/null || true
          ls -1 ./output/participantes_procesado_*.csv 2>/dev/null || true

      # Garantiza que hay algo que subir (si no, falla el 03)
      - name: Assert outputs exist
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=( ./output/*events_*.csv ./output/*participantes_*.csv ./output/participantes*.json ./output/participantes_procesado_*.csv )
          echo "Ficheros a subir: ${files[*]:-<ninguno>}"
          if [ ${#files[@]} -eq 0 ]; then
            echo "::error::No hay ficheros de salida para subir (revisa nombres y OUT_DIR)"; exit 1
          fi

      - name: Upload processed participants (JSON+CSV)
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-processed
          path: |
            ./output/*events_*.csv
            ./output/*participantes_*.csv
            ./output/participantes.json
            ./output/participantes_*.json
            ./output/participantes_procesado_*.csv
            ./output/*progress_*.json
          if-no-files-found: error
          retention-days: 5
