name: "03 - Participantes (scrape + process)"

on:
  workflow_run:
    workflows: ["02 - INFO desde 01events"]
    types: [completed]
  workflow_dispatch: {}
  schedule:
    - cron: "3 4 * * *"

permissions:
  contents: read
  actions: read

concurrency:
  group: participantes-03
  cancel-in-progress: true

jobs:
  run_and_upload:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      TZ: Europe/Madrid
      OUT_DIR: ./output
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS:  ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
      FILE_PREFIX: "03"

      # Ritmo y límites “polite”
      LIMIT_EVENTS: "15"
      LIMIT_PARTICIPANTS: "60"
      SLOW_MIN_S: "1.2"
      SLOW_MAX_S: "3.0"
      SCROLL_WAIT_S: "2.5"
      MAX_SCROLLS: "10"
      PER_PART_TIMEOUT_S: "8"
      RENDER_POLL_S: "0.35"
      CLICK_RETRIES: "2"
      MAX_EVENT_SECONDS: "600"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install selenium webdriver-manager beautifulsoup4 python-dotenv pandas python-dateutil numpy

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run 03_eventosproxParticipantes.py (all) with hard timeout
        id: run03
        shell: bash
        timeout-minutes: 60
        run: |
          set -euo pipefail
          test -f "./03_eventosproxParticipantes.py" || { echo "::error::No se encontró 03_eventosproxParticipantes.py"; exit 1; }
          if ! timeout 55m python "./03_eventosproxParticipantes.py" all; then
            echo "::error::03_eventosproxParticipantes.py superó el tiempo"
            pkill -9 -f chrome || true
            pkill -9 -f chromedriver || true
            exit 1
          fi

      - name: List outputs
        shell: bash
        run: |
          set -euo pipefail
          echo "Contenido de ${OUT_DIR}:"
          ls -la "${OUT_DIR}" || true
          echo "---"
          ls -1 ${OUT_DIR}/*events_*.csv 2>/dev/null || true
          ls -1 ${OUT_DIR}/*participantes_*.csv 2>/dev/null || true
          ls -1 ${OUT_DIR}/participantes*.json 2>/dev/null || true
          ls -1 ${OUT_DIR}/*progress_*.json 2>/dev/null || true
          ls -1 ${OUT_DIR}/participantes_procesado_*.csv 2>/dev/null || true

      - name: Assert outputs exist
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=( ${OUT_DIR}/*events_*.csv ${OUT_DIR}/*participantes_*.csv ${OUT_DIR}/participantes*.json ${OUT_DIR}/participantes_procesado_*.csv )
          echo "Ficheros a subir: ${files[*]:-<ninguno>}"
          if [ ${#files[@]} -eq 0 ]; then
            echo "::error::No hay ficheros de salida para subir (revisa nombres y OUT_DIR)"; exit 1
          fi

      - name: Upload participants bundle
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-processed
          path: |
            ./output/*events_*.csv
            ./output/*participantes_*.csv
            ./output/participantes.json
            ./output/participantes_*.json
            ./output/participantes_procesado_*.csv
            ./output/*progress_*.json
          if-no-files-found: error
          retention-days: 5
