name: 03 - Participantes (scrape + process)

on:
  workflow_run:
    workflows: ["02 - INFO desde 01events"]
    types: [completed]
  workflow_dispatch: {}
  schedule:
    - cron: '3 4 * * *'

concurrency:
  group: participantes-03
  cancel-in-progress: true

jobs:
  run_and_upload:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
      OUT_DIR: ./output
      FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
      FLOW_PASS: ${{ secrets.FLOW_PASS }}
      HEADLESS: "true"
      INCOGNITO: "true"
      FILE_PREFIX: "03"
      LIMIT_EVENTS: "0"
      LIMIT_PARTICIPANTS: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager beautifulsoup4 python-dotenv pandas python-dateutil numpy
          fi

      - name: Ejecutar 03 (all: scrape + process)
        run: python "./03_eventosproxParticipantes.py" all

      - name: Mostrar outputs
        run: |
          echo "Contenido de $OUT_DIR:"
          ls -la "$OUT_DIR" || true
          echo "Previstos:"
          ls -1 output/*events_*.csv 2>/dev/null || true
          ls -1 output/*participantes_*.csv 2>/dev/null || true
          ls -1 output/participantes*.json 2>/dev/null || true
          ls -1 output/*progress_*.json 2>/dev/null || true
          ls -1 output/participantes_procesado_*.csv 2>/dev/null || true

      - name: Subir artefactos (JSON+CSV)
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-processed
          path: |
            output/*events_*.csv
            output/*participantes_*.csv
            output/participantes.json
            output/participantes_*.json
            output/participantes_procesado_*.csv
            output/*progress_*.json
          if-no-files-found: error
          retention-days: 5

      - name: (FTPS) Subir outputs 3 para debug
        if: always()
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          BASE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/ListadoEventos/Workflows/03"
          TS="$(date -u +'%Y%m%dT%H%M%SZ')"
          shopt -s nullglob
          for f in output/*; do
            [ -f "$f" ] || continue
            bn="$(basename "$f")"
            curl --fail --ssl-reqd --ftp-create-dirs --disable-epsv --ftp-skip-pasv-ip \
                 --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
                 --upload-file "$f" "${BASE}/${bn}"
            curl --fail --ssl-reqd --disable-epsv --ftp-skip-pasv-ip \
                 --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
                 --upload-file "$f" "${BASE}/${TS}_${bn}"
          done
