name: 03 - Participantes por evento

on:
  workflow_run:
    workflows: ["02 - INFO desde 01events"]
    types: [completed]

jobs:
  produce_participants:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Madrid
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Descargar artefacto 02info
        uses: actions/download-artifact@v4
        with:
          name: a02-02info-json
          path: ./artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ejecutar 03_eventosproxParticipantes.py
        run: |
          mkdir -p output/participants
          python "./03_eventosproxParticipantes.py" "./artifacts/02competiciones_detalladas.json" "./output/participants"

      - name: Comprobar ficheros generados
        run: |
          shopt -s nullglob
          count=(./output/participants/*.json)
          echo "Total participantes JSON: ${#count[@]}"
          test ${#count[@]} -gt 0

      - name: Subir artefacto participantes (carpeta completa)
        uses: actions/upload-artifact@v4
        with:
          name: a03-participants-jsons
          path: |
            ./output/participants/*.json
          if-no-files-found: error
          retention-days: 7
