name: 04 Union participantes

on:
  workflow_dispatch: {}
  schedule:
    - cron: "25 5 * * *"   # cuando quieras

jobs:
  union:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    env:
      OUT_DIR: ./output

    steps:
      - uses: actions/checkout@v4

      - name: Ensure output dir
        run: mkdir -p "$OUT_DIR"

      # 1) Buscar el último run exitoso del workflow 03
      - name: Get latest successful run of 03
        id: getrun
        uses: actions/github-script@v7
        with:
          script: |
            const wfFile = '03_participantes.yml'; // <-- nombre del fichero del workflow 03
            const res = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: wfFile,
              status: 'success',
              per_page: 1
            });
            if (!res.data.workflow_runs.length) {
              core.setFailed(`No successful runs for ${wfFile}`);
              return;
            }
            core.setOutput('run_id', res.data.workflow_runs[0].id);

      # 2) Descargar artefactos del 03 por NOMBRE (tiene que coincidir con el upload del 03)
      - name: Download artifacts from 03
        uses: actions/download-artifact@v4
        with:
          name: a03-participants-processed           # <-- el mismo name que sube el 03
          run-id: ${{ steps.getrun.outputs.run_id }} # <-- muy importante
          merge-multiple: true
          path: ${{ env.OUT_DIR }}

      - name: Debug listing
        run: |
          echo "Contenido de $OUT_DIR:"
          ls -la "$OUT_DIR" || true
          echo "Ficheros:"
          find "$OUT_DIR" -maxdepth 1 -type f -printf "%f\n" || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run union
        run: |
          python ./04_eventosproxUnion.py "$OUT_DIR" "$OUT_DIR/participantes_completos_final.json"

      - name: Upload final
        uses: actions/upload-artifact@v4
        with:
          name: a04-participantes-final
          path: ${{ env.OUT_DIR }}/participantes_completos_final.json
          if-no-files-found: error
