name: Calendario RSCE diario

on:
  schedule:
    # 04:05 UTC ≈ 06:05 en Europa/Madrid (horario de verano).
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: Europe/Madrid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias (si existen)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar script que genera el CSV
        run: |
          python "./Calendario RSCE 25.08.22.py"
          ls -l
          test -f "eventos_agility_2025.csv"

      - name: Calcular hash local del CSV
        id: hash
        run: |
          LOCAL_HASH=$(sha256sum eventos_agility_2025.csv | awk '{print $1}')
          echo "LOCAL_HASH=$LOCAL_HASH" >> "$GITHUB_OUTPUT"
          echo "➡ Hash local: $LOCAL_HASH"

      - name: Crear carpeta remota (por si no existe)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            mkdir -p /home/agilitydivertidog/www/NewWeb/Privado/Calendar

      - name: Copiar CSV al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "eventos_agility_2025.csv"
          target: "/home/agilitydivertidog/www/NewWeb/Privado/Calendar/"
          overwrite: true

      - name: Verificar en servidor (existe, tamaño, líneas y hash)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            FILE="/home/agilitydivertidog/www/NewWeb/Privado/Calendar/eventos_agility_2025.csv"
            test -f "$FILE"
            ls -lh "$FILE"
            echo "➡ Cabecera:"
            head -n 2 "$FILE" || true
            echo "➡ Nº de líneas:"
            wc -l "$FILE" || true
            REMOTE_HASH=$(sha256sum "$FILE" | awk '{print $1}')
            echo "➡ Hash remoto: $REMOTE_HASH"
            if [ "$REMOTE_HASH" != "${{ steps.hash.outputs.LOCAL_HASH }}" ]; then
              echo "ERROR: El hash remoto no coincide con el local"; exit 1
            fi
            chmod 644 "$FILE"

      # (Opcional) Guardar una copia histórica con fecha AAAA-MM-DD
     - name: Archivar copia con fecha (opcional)
  if: always()
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    password: ${{ secrets.SSH_PASSWORD }}
    port: ${{ secrets.SSH_PORT }}
    script: |
      set -euo pipefail
      DIR="/home/agilitydivertidog/www/NewWeb/Privado/Calendar"
      FILE="$DIR/eventos_agility_2025.csv"
      test -s "$FILE"  # existe y no está vacío
      D=$(date +%F)
      cp -f "$FILE" "$DIR/eventos_agility_2025_${D}.csv"
